"""add agencies and agency_page tables

Revision ID: df8f140cd3eb
Revises: ad4f9dd22e2d
Create Date: 2026-10-02 18:38:31.815089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8f140cd3eb'
down_revision: Union[str, None] = 'ad4f9dd22e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agency_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('title_uz', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('text_uz', sa.String(), nullable=False),
    sa.Column('text_ru', sa.String(), nullable=False),
    sa.Column('text_en', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_page')
    op.drop_table('agencies')
    # ### end Alembic commands ###
